name: calendar_pro_farhad
description: "A modern and accurate calendar for Flutter that supports both Jalali (Solar) and Gregorian date systems with a minimal design and diverse styles."
version: 0.0.1
homepage: https://github.com/farhadrezvani7/calendar_pro_farhad

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shamsi_date: ^1.0.4
  flutter_svg: ^2.0.16
  vector_graphics: ^1.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IRANSansXFA-Regular
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Regular.ttf
    - family: IRANSansXFA-Medium
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Medium.ttf
    - family: IRANSansXFA-DemiBold
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-DemiBold.ttf
    - family: IRANSansXFA-Bold
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
flutter_gen:
  integrations:
    flutter_svg: true
